name: deploy

on:
  push:
    branches:
      - main 
        feature/devops # on dev only


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: build Docker image
      run: docker build -t pokeapi:latest .
    - name: deploy to app Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl auth token "$FLY_API_TOKEN"
        flyctl deploy --remote-only --image pokeapi:latest
