name: test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Clojure
              run: curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh |
                chmod +x linux-install.sh | 
                sudo ./linux-install.sh
            - name: lint
              run: clj -M:lint
            - name: test
              run: clj -M:test
