name: test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Clojure
              run: |
                curl -O https://download.clojure.org/install/linux-install-1.11.1.1238.sh
                chmod +x linux-install-1.11.1.1238.sh
                sudo ./linux-install-1.11.1.1238.sh
            - name: lint
              run: clj -M:lint
            - name: test
              run: clj -M:test
