name: test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install clojure tools
              uses: DeLaGuardo/setup-clojure@12.1
            - name: lint
              run: clj -M:lint
            - name: test
              run: clj -M:test
